In [ ]:
import librosa
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import itertools
import librosa.display
%matplotlib inline
import os
import csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import keras
import wave
import tensorflow as tf

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [ ]:
# header = 'filename'
# for i in range(1, 41):
#   header += f' mfcc{i}'
# header += ' label'
# header = header.split()

In [ ]:
# file = open('data.csv', 'w', newline='')
# with file:
#   writer = csv.writer(file)
#   writer.writerow(header)
# songname = f'/content/heartbeat-01a.wav'
# y, sr = librosa.load(songname, mono=True, duration=3, sr=8000)
# mfcc = librosa.feature.mfcc(y=y, sr=8000, n_mfcc=40, n_fft=2048, hop_length=512, n_mels=128)
# to_append = f'Signal'
# for e in mfcc:
#   to_append += f' {np.mean(e.T, axis=0)}'
# file = open('data.csv', 'a', newline='')
# with file:
#   writer = csv.writer(file)
#   writer.writerow(to_append.split())

In [ ]:
# wav1 = wave.open(songname)
# wav1.getframerate()

48000

In [ ]:
# def preprocess(file_path, num_mfcc=20, n_fft=2048, hop_length=512):
#   """
#   """

#   signal, sample_rate = librosa.load(file_path)
#   mfccs = librosa.feature.mfcc(signal, sample_rate, n_mfcc=num_mfcc, n_fft=n_fft, hop_length=hop_length)
#   return mfccs.T

In [ ]:
# data = pd.read_csv('data.csv')
# data = data.drop(['filename', 'label'], axis=1)
# data.head()

mfcc1      mfcc2      mfcc3      mfcc4      mfcc5      mfcc6  \
0 -498.021362  66.468208  56.749767  43.715694  30.659632  20.085905   

       mfcc7    mfcc8     mfcc9    mfcc10  ...    mfcc31    mfcc32    mfcc33  \
0  12.972437  8.84836  6.488301  4.739157  ... -1.937624 -1.916357 -2.041268   

     mfcc34    mfcc35    mfcc36    mfcc37    mfcc38    mfcc39    mfcc40  
0 -2.186869 -2.244253 -2.178258 -2.027719 -1.862408 -1.734782 -1.657939  

[1 rows x 40 columns]

In [ ]:
scaler = StandardScaler()
# X = np.array(data.iloc[:, :], dtype=float)
# X = np.reshape(X, (X.shape[0], 40, 1, 1))
# # print(X)
# X.shape

(1, 40, 1, 1)

In [ ]:
# interpreter = tf.lite.Interpreter(model_path="model.tflite")
# interpreter.allocate_tensors()

# input_details = interpreter.get_input_details()
# output_details = interpreter.get_output_details()

# input_shape = input_details[0]['shape']
# input_data = np.array(X, dtype=np.float32)
# interpreter.set_tensor(input_details[0]['index'], input_data)

# interpreter.invoke()

# output_data = interpreter.get_tensor(output_details[0]['index'])
# print(output_data)
# output_data.shape

[[1.2534349e-07 1.5231032e-02 1.3634328e-03 4.0865167e-08 9.8340535e-01]]


(1, 5)

In [ ]:
# print(input_details)
# print(output_details)

[{'name': 'conv2d_input', 'index': 0, 'shape': array([ 1, 40,  1,  1], dtype=int32), 'shape_signature': array([-1, 40,  1,  1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
[{'name': 'Identity', 'index': 20, 'shape': array([1, 5], dtype=int32), 'shape_signature': array([-1,  5], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]


In [ ]:
# np.argmax(output_data)

4

In [ ]:
# print("Prediksi Jantung: \n")
# print("AS: "+str(output_data[0,0]*100)+"%")
# print("MR: "+str(output_data[0,1]*100)+"%")
# print("MS: "+str(output_data[0,2]*100)+"%")
# print("MVP: "+str(output_data[0,3]*100)+"%")
# print("Normal: "+str(output_data[0,4]*100)+"%")

Prediksi Jantung: 

AS: 1.2534349025372649e-05%
MR: 1.523103192448616%
MS: 0.13634328497573733%
MVP: 4.0865167250103696e-06%
Normal: 98.3405351638794%


In [ ]:
# plt.style.use('ggplot')

# dic = {'Aortic Stenosis': output_data[0,0],
#        'Mitral Regurgitation': output_data[0,1],
#        'Mitral Stenosis': output_data[0,2],
#        'Mitral Valve Prolapse': output_data[0,3],
#        'Normal': output_data[0,4]}

# # group together all elements in the dictionary whose value is less than 2
# # name this group 'All the rest'
# newdic={}
# for key, group in itertools.groupby(dic, lambda k: 'Kategori Lain' if (dic[k]<0.01) else k):
#      newdic[key] = sum([dic[k] for k in list(group)])   

# labels = newdic.keys()
# sizes = newdic.values()
# fig, ax = plt.subplots(figsize=(12,8))
# ax.pie(sizes, labels=labels, autopct='%1.2f%%', startangle=0)
# ax.axis('equal')
# plt.tight_layout()
# plt.title("Prediksi Jantung")
# plt.show()

In [ ]:
from sklearn.svm import SVC  
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
data = pd.read_csv('/content/gdrive/MyDrive/Dataset_HVD/data.csv')
data.head()

filename  chroma_stft      rmse  spectral_centroid  \
0  New_AS_001.wav     0.532519  0.158163         340.667541   
1  New_AS_002.wav     0.534369  0.158338         339.195538   
2  New_AS_003.wav     0.539327  0.158026         339.593619   
3  New_AS_004.wav     0.532994  0.157684         334.603804   
4  New_AS_005.wav     0.522509  0.155256         332.784894   

   spectral_bandwidth     rolloff  zero_crossing_rate       mfcc1       mfcc2  \
0          436.372017  562.054713            0.027862 -395.073944  101.916969   
1          449.269377  544.904375            0.027400 -392.596954  102.263245   
2          445.402603  544.046858            0.026985 -395.947357  103.724045   
3          443.271544  535.376409            0.028670 -395.410065  102.333733   
4          433.666385  529.183231            0.027620 -398.008179  103.003098   

       mfcc3  ...    mfcc12    mfcc13    mfcc14    mfcc15    mfcc16    mfcc17  \
0  60.079845  ...  0.301374  0.244905 -0.594042 -1.977559 -1.481203 -1.701962   
1  55.993614  ...  1.115721  0.951022 -0.984761 -2.548201 -1.132616 -1.703537   
2  56.769585  ...  0.366322  0.627108 -0.364678 -1.960979 -1.390954 -2.237176   
3  57.058868  ...  0.046287  0.131367 -0.711598 -2.198510 -1.430536 -1.801373   
4  57.432564  ... -0.250010 -0.241696 -0.561792 -2.151547 -1.528064 -1.446120   

     mfcc18    mfcc19    mfcc20  label  
0 -1.789857 -1.403314 -2.538552     AS  
1 -1.859431 -0.697074 -2.358541     AS  
2 -1.881434 -0.531128 -2.354584     AS  
3 -1.563430 -0.394315 -1.946569     AS  
4 -1.647285 -1.720251 -3.283127     AS  

[5 rows x 28 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   filename            1000 non-null   object 
 1   chroma_stft         1000 non-null   float64
 2   rmse                1000 non-null   float64
 3   spectral_centroid   1000 non-null   float64
 4   spectral_bandwidth  1000 non-null   float64
 5   rolloff             1000 non-null   float64
 6   zero_crossing_rate  1000 non-null   float64
 7   mfcc1               1000 non-null   float64
 8   mfcc2               1000 non-null   float64
 9   mfcc3               1000 non-null   float64
 10  mfcc4               1000 non-null   float64
 11  mfcc5               1000 non-null   float64
 12  mfcc6               1000 non-null   float64
 13  mfcc7               1000 non-null   float64
 14  mfcc8               1000 non-null   float64
 15  mfcc9               1000 non-null   float64
 16  mfcc10 

In [ ]:
X = scaler.fit_transform(data.iloc[:, 7:-1])
y = data.iloc[:, -1]

In [ ]:
X

array([[ 1.64173956,  0.44493528,  0.61035895, ...,  0.15931573,
         0.05839942, -0.11068757],
       [ 1.6996639 ,  0.45694029,  0.36894314, ...,  0.12140232,
         0.43088161, -0.01753243],
       [ 1.62131482,  0.50758475,  0.41478772, ...,  0.10941179,
         0.51840385, -0.01548455],
       ...,
       [-0.10306209, -0.1580842 ,  0.87299322, ..., -0.18373122,
        -0.38416711, -0.41585439],
       [-0.02487715, -0.22669821,  0.81202676, ..., -0.11494275,
        -0.34328144, -0.52490163],
       [ 0.15494049, -0.14947355,  0.65963371, ..., -0.68958306,
        -0.30415242, -0.14117206]])

In [ ]:
y.head()

0    AS
1    AS
2    AS
3    AS
4    AS
Name: label, dtype: object

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
y_test.value_counts()

MS     40
AS     40
MR     40
MVP    40
N      40
Name: label, dtype: int64

In [ ]:
X_train.shape

(800, 20)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

# Instantiate an RBF SVM
svm = SVC(probability=True)

# Instantiate the GridSearchCV object and run the search
parameters = {'C':[0.1, 1, 10], 'gamma':[0.00001, 0.0001, 0.001, 0.01, 0.1] ,'kernel':['rbf', 'poly', 'sigmoid']}
searcher = GridSearchCV(svm, parameters, cv=5)
searcher.fit(X_train, y_train)

# Report the best parameters and the corresponding score
print("Best CV params:", searcher.best_params_)
print("Best CV accuracy:", searcher.best_score_)

# Report the test accuracy using these best parameters
print("Test accuracy of best grid search hypers:", searcher.score(X_test, y_test))

Best CV params: {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}
Best CV accuracy: 0.99125
Test accuracy of best grid search hypers: 1.0


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
grid_predictions = searcher.predict(X_test)
print(confusion_matrix(y_test,grid_predictions))
print(classification_report(y_test,grid_predictions))

[[40  0  0  0  0]
 [ 0 40  0  0  0]
 [ 0  0 40  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 40]]
              precision    recall  f1-score   support

          AS       1.00      1.00      1.00        40
          MR       1.00      1.00      1.00        40
          MS       1.00      1.00      1.00        40
         MVP       1.00      1.00      1.00        40
           N       1.00      1.00      1.00        40

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200



In [ ]:
header = 'filename'
for i in range(1, 21):
  header += f' mfcc{i}'
header += ' label'
header = header.split()

file = open('data.csv', 'w', newline='')
with file:
  writer = csv.writer(file)
  writer.writerow(header)
songname = f'/content/heartbeat-01a.wav'
y, sr = librosa.load(songname, mono=True, duration=3, sr=8000)
mfcc = librosa.feature.mfcc(y=y, sr=8000, n_mfcc=20, n_fft=2048, hop_length=512, n_mels=128)
to_append = f'Signal'
for e in mfcc:
  to_append += f' {np.mean(e.T, axis=0)}'
file = open('data.csv', 'a', newline='')
with file:
  writer = csv.writer(file)
  writer.writerow(to_append.split())

wav1 = wave.open(songname)
wav1.getframerate()

data = pd.read_csv('data.csv')
data = data.drop(['filename', 'label'], axis=1)
data.head()

In [ ]:
result = searcher.predict_proba(data)

print("Prediksi Kondisi Katup Jantung: \n")
print("Aortic Stenosi: {0:.2%}".format(result[0, 0]))
print("Mitral Regurgitation: {0:.2%}".format(result[0, 1]))
print("Mitral Stenosis: {0:.2%}".format(result[0, 2]))
print("Mitral Valve Prolapse: {0:.2%}".format(result[0, 3]))
print("Normal: {0:.2%}".format(result[0, 4]))

Prediksi Kondisi Katup Jantung: 

Aortic Stenosi: 11.26%
Mitral Regurgitation: 24.38%
Mitral Stenosis: 29.07%
Mitral Valve Prolapse: 34.24%
Normal: 1.06%


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


In [ ]:
# from sklearn.linear_model import SGDClassifier

# # We set random_state=0 for reproducibility 
# linear_classifier = SGDClassifier(random_state=0)

# # Instantiate the GridSearchCV object and run the search
# parameters = {'alpha':[0.00001, 0.0001, 0.001, 0.01, 0.1, 1], 
#              'loss':['hinge', 'log_loss']}
# searcher = GridSearchCV(linear_classifier, parameters, cv=10)
# searcher.fit(X_train, y_train)

# # Report the best parameters and the corresponding score
# print("Best CV params", searcher.best_params_)
# print("Best CV accuracy", searcher.best_score_)
# print("Test accuracy of best grid search hypers:", searcher.score(X_test, y_test))

In [ ]:
# def keras_classifier(optimizer):
#     x = Convolution2D(32, (4,4), padding="same")(inp)
#     x = BatchNormalization()(x)
#     x = Activation("relu")(x)
#     x = MaxPool2D()(x)
    
#     x = Convolution2D(32*2, (4,10), padding="same")(x)
#     x = BatchNormalization()(x)
#     x = Activation("relu")(x)
#     x = MaxPool2D()(x)
    
#     x = Convolution2D(32*3, (4,10), padding="same")(x)
#     x = BatchNormalization()(x)
#     x = Activation("relu")(x)
#     x = MaxPool2D()(x)
    
#     x = Convolution2D(32*3, (4,10), padding="same")(x)
#     x = BatchNormalization()(x)
#     x = Activation("relu")(x)
#     x = MaxPool2D()(x)

#     x = Flatten()(x)
#     x = Dense(64)(x)
#     x = BatchNormalization()(x)
#     x = Activation("relu")(x)
#     out = Dense(nclass, activation=softmax)(x)


#     cf = Sequential()
#     cf.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'relu', input_dim = 7))
#     cf.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'relu'))
#     cf.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
#     cf.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
#     return cf

# cf = KerasClassifier(build_fn = keras_classifier)
# parameters = {'batch_size': [2, 4, 8, 16],
#               'epochs': [32, 64],
#               'optimizer': ['adam', 'rmsprop']}
# gv_search = GridSearchCV(estimator = cf,
#                            param_grid = parameters,
#                            scoring = 'accuracy',
#                            cv = 5)
# gv_search = gv_search.fit(X_train_scaled, y_train)
# best_param = gv_search.best_params_
# best_acc = gv_search.best_score_

# print(best_param, best_acc)